from .base import ApiController
from .user import (
    UserController,
    UserProfileController,
    user_controller,
    user_profile_controller,
)
from .tag import TagController, TagRelationController, tag_controller, tag_relation_controller
from .article import (
    ArticleController,
    ArticleRecommendationController,
    ArticleRewardRankingController,
    article_controller,
    article_recommendation_controller,
    article_reward_ranking_controller,
)
from .activity import (
    RewardController,
    UserFavoriteController,
    UserInterestController,
    UserLikeController,
    UserViewHistoryController,
    reward_controller,
    user_favorite_controller,
    user_interest_controller,
    user_like_controller,
    user_view_history_controller,
)
from .shop import (
    GoodController,
    GoodChoiceController,
    GoodCommentController,
    GoodCommentLikeController,
    good_controller,
    good_choice_controller,
    good_comment_controller,
    good_comment_like_controller,
)

__all__ = [
    "ApiController",
    "ArticleController",
    "ArticleRecommendationController",
    "ArticleRewardRankingController",
    "RewardController",
    "TagController",
    "TagRelationController",
    "UserController",
    "UserFavoriteController",
    "UserInterestController",
    "UserLikeController",
    "UserProfileController",
    "UserViewHistoryController",
    "GoodController",
    "GoodChoiceController",
    "GoodCommentController",
    "GoodCommentLikeController",
    "article_controller",
    "article_recommendation_controller",
    "article_reward_ranking_controller",
    "reward_controller",
    "tag_controller",
    "tag_relation_controller",
    "user_controller",
    "user_favorite_controller",
    "user_interest_controller",
    "user_like_controller",
    "user_profile_controller",
    "user_view_history_controller",
    "good_controller",
    "good_choice_controller",
    "good_comment_controller",
    "good_comment_like_controller",
]
