from .base import ApiController
from .user import (
    UserController,
    UserProfileController,
    user_controller,
    user_profile_controller,
)
from .tag import (
    ArticleTagController,
    CrossRoleTagController,
    RoleTagController,
    article_tag_controller,
    cross_role_tag_controller,
    role_tag_controller,
)
from .article import (
    ArticleController,
    ArticleRecommendationController,
    ArticleRewardRankingController,
    article_controller,
    article_recommendation_controller,
    article_reward_ranking_controller,
)
from .activity import (
    RewardController,
    UserFavoriteController,
    UserInterestController,
    UserLikeController,
    UserViewHistoryController,
    reward_controller,
    user_favorite_controller,
    user_interest_controller,
    user_like_controller,
    user_view_history_controller,
)

__all__ = [
    "ApiController",
    "ArticleController",
    "ArticleRecommendationController",
    "ArticleRewardRankingController",
    "ArticleTagController",
    "CrossRoleTagController",
    "RewardController",
    "RoleTagController",
    "UserController",
    "UserFavoriteController",
    "UserInterestController",
    "UserLikeController",
    "UserProfileController",
    "UserViewHistoryController",
    "article_controller",
    "article_recommendation_controller",
    "article_reward_ranking_controller",
    "article_tag_controller",
    "cross_role_tag_controller",
    "reward_controller",
    "role_tag_controller",
    "user_controller",
    "user_favorite_controller",
    "user_interest_controller",
    "user_like_controller",
    "user_profile_controller",
    "user_view_history_controller",
]
