from .user import (
    UserCreate,
    UserProfileCreate,
    UserProfileUpdate,
    UserUpdate,
)
from .tag import (
    ArticleTagCreate,
    ArticleTagUpdate,
    CrossRoleTagCreate,
    CrossRoleTagUpdate,
    RoleTagCreate,
    RoleTagUpdate,
)
from .article import (
    ArticleCreate,
    ArticleRecommendationCreate,
    ArticleRecommendationUpdate,
    ArticleRewardRankingCreate,
    ArticleRewardRankingUpdate,
    ArticleUpdate,
)
from .activity import (
    RewardCreate,
    RewardUpdate,
    UserFavoriteCreate,
    UserFavoriteUpdate,
    UserInterestCreate,
    UserInterestUpdate,
    UserLikeCreate,
    UserLikeUpdate,
    UserViewHistoryCreate,
    UserViewHistoryUpdate,
)

__all__ = [
    "UserCreate",
    "UserUpdate",
    "UserProfileCreate",
    "UserProfileUpdate",
    "RoleTagCreate",
    "RoleTagUpdate",
    "CrossRoleTagCreate",
    "CrossRoleTagUpdate",
    "ArticleTagCreate",
    "ArticleTagUpdate",
    "ArticleCreate",
    "ArticleUpdate",
    "ArticleRewardRankingCreate",
    "ArticleRewardRankingUpdate",
    "ArticleRecommendationCreate",
    "ArticleRecommendationUpdate",
    "UserViewHistoryCreate",
    "UserViewHistoryUpdate",
    "UserFavoriteCreate",
    "UserFavoriteUpdate",
    "UserLikeCreate",
    "UserLikeUpdate",
    "RewardCreate",
    "RewardUpdate",
    "UserInterestCreate",
    "UserInterestUpdate",
]
