from .user import (
    UserCreate,
    UserProfileCreate,
    UserProfileUpdate,
    UserUpdate,
)
from .tag import TagCreate, TagRelationCreate, TagRelationUpdate, TagType, TagUpdate
from .article import (
    ArticleCreate,
    ArticleRecommendationCreate,
    ArticleRecommendationUpdate,
    ArticleRewardRankingCreate,
    ArticleRewardRankingUpdate,
    ArticleUpdate,
)
from .activity import (
    RewardCreate,
    RewardUpdate,
    UserFavoriteCreate,
    UserFavoriteUpdate,
    UserInterestCreate,
    UserInterestUpdate,
    UserLikeCreate,
    UserLikeUpdate,
    UserViewHistoryCreate,
    UserViewHistoryUpdate,
)
from .shop import (
    GoodCreate,
    GoodWithChoicesCreate,
    GoodUpdate,
    GoodChoiceCreate,
    GoodChoiceUpdate,
    GoodCommentCreate,
    GoodCommentUpdate,
    GoodCommentLikeCreate,
    GoodCommentLikeUpdate,
)
from .buy_or_cart import CartCreate, CartUpdate
from .draft import DraftCreate, DraftUpdate, DraftOut

__all__ = [
    "UserCreate",
    "UserUpdate",
    "UserProfileCreate",
    "UserProfileUpdate",
    "TagCreate",
    "TagUpdate",
    "TagType",
    "TagRelationCreate",
    "TagRelationUpdate",
    "ArticleCreate",
    "ArticleUpdate",
    "ArticleRewardRankingCreate",
    "ArticleRewardRankingUpdate",
    "ArticleRecommendationCreate",
    "ArticleRecommendationUpdate",
    "UserViewHistoryCreate",
    "UserViewHistoryUpdate",
    "UserFavoriteCreate",
    "UserFavoriteUpdate",
    "UserLikeCreate",
    "UserLikeUpdate",
    "RewardCreate",
    "RewardUpdate",
    "UserInterestCreate",
    "UserInterestUpdate",
    "GoodCreate",
    "GoodWithChoicesCreate",
    "GoodUpdate",
    "GoodChoiceCreate",
    "GoodChoiceUpdate",
    "GoodCommentCreate",
    "GoodCommentUpdate",
    "GoodCommentLikeCreate",
    "GoodCommentLikeUpdate",
    "CartCreate",
    "CartUpdate",
    "DraftCreate",
    "DraftUpdate",
    "DraftOut",
]
